### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by pasindu20** [Dreamvast/Dreamvast-main-bot#1]
What the deference between client and superclient ?
What the deference between original erela.js and this git has custom erela.js ?

**Comment by RainyXeon** [comment]
@pasindu20 
The client in my bot is just the superclient's declaration to run it.  The superclient is my bot's main module, which calls other modules including events, commands, custom modes, sharding, and login functions.  The original version of erela.js and the custom version of erela.js by Adivise are not fundamentally different.  It's just a simpler way to adjust the nightcore.

**Comment by pasindu20** [comment]
> @pasindu20 The client in my bot is just the superclient's declaration to run it. The superclient is my bot's main module, which calls other modules including events, commands, custom modes, sharding, and login functions. The original version of erela.js and the custom version of erela.js by Adivise are not fundamentally different. It's just a simpler way to adjust the nightcore.

Add https://www.npmjs.com/package/discord-hybrid-sharding > sharding to this git i try to add it but i can't figure it out
 because i never used super client before can you add sharding system to this git

**Comment by RainyXeon** [comment]
@pasindu20 
I'll find out and put it in git later.

**Comment by pasindu20** [comment]
> @pasindu20 I'll find out and put it in git later.

I created my own music bot (sharded version and it use 10 guilds  = ram useage 120mb)
and this git use on 10 guild about 65mb pretty well optimized and no memory leeks

i suggest make sharded version as well 
on main bot on 11k guilds and it use 5gb ram its so much that why i rewrite no memory leaks version

**Comment by pasindu20** [comment]
> > @pasindu20 I'll find out and put it in git later.
> 
> I created my own music bot (sharded version and it use 10 guilds = ram useage 120mb) and this git use on 10 guild about 65mb pretty well optimized and no memory leeks
> 
> i suggest make sharded version as well on main bot on 11k guilds and it use 5gb ram its so much that why i rewrite no memory leaks version

Is shokaku better then erela.js i see most top tire music bots useing shokaku

**Comment by pasindu20** [comment]
Is shokaku better then erela.js i see most top tire music bots useing shokaku

**Comment by RainyXeon** [comment]
@pasindu20 
I don't think there's much difference other than the syntax and cute logo.  I never do it before.  But I find using erela.js it's still quite good because it has a lot of features such as filter, lavalink server information... besides I find it easier to use.
