### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by pasindu20** [Dreamvast/Dreamvast-main-bot#2]
Why deleteing slash command add slash command to this repo

**Comment by RainyXeon** [comment]
This is the feature i forgot is the notification that it will be deleted, so it doesn't matter if you enable or not in my bot, it will be more helpful in finding the prefix at the present time.

**Comment by pasindu20** [comment]
> This is the feature i forgot is the notification that it will be deleted, so it doesn't matter if you enable or not in my bot, it will be more helpful in finding the prefix at the present time.

discord says they remove prefix like they added Message Intence

**Comment by RainyXeon** [comment]
@pasindu20 
Yea, and I prepared for that by creating a slash version of Dreamvast and directly updating the old features of the prefix version.
