### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by pasindu20** [Dreamvast/Dreamvast-main-bot#3]
I see some issues on if i set (!@#$%^&*()_) this as prefix bot not save mongo db 
 when bot join frist time guild and after prefix is not responding to any commands 
 
if you have any discord server its more faster then open issue on github

**Comment by RainyXeon** [comment]
@pasindu20 
Can you record that issue in a video, post it on youtube, make it unlisted, and post it here?

**Comment by pasindu20** [comment]
> @pasindu20 Can you record that issue in a video, post it on youtube, make it unlisted, and post it here?

mm i currently don't have recording software on my pc but 
try the code with prefix=# and make new table on mongo and start bot then ping the bot it will say 
**my prefix is ``** like this msg that means guild data not saved in mongo

**Comment by RainyXeon** [comment]
@pasindu20 
I think if the 'prefix=#' is the command as you say, it may be because in the prefix.js file, it only stores the prefixes after the spaces (eg: @prefix $) then it will save the prefix. And if it's code, I'm not sure which part of the code in which file it is.

**Comment by pasindu20** [comment]
> @pasindu20 I think if the 'prefix=#' is the command as you say, it may be because in the prefix.js file, it only stores the prefixes after the spaces (eg: @Prefix $) then it will save the prefix. And if it's code, I'm not sure which part of the code in which file it is.

i try prefix= # to and it will save empty space on mongo db not save actual (#) prefix

**Comment by pasindu20** [comment]
give me your discord server link it more faster then chatting here

**Comment by RainyXeon** [comment]
@pasindu20 
I don't have a discord server. Can you create one and let me join?

**Comment by pasindu20** [comment]
> @pasindu20 I don't have a discord server. Can you create one and let me join?

https://discord.gg/ercVaHxA

**Comment by RainyXeon** [comment]
Bug fixed
